// Generated by `pnpm build:serverless` before Vercel collects function files.
// @ts-expect-error The build artifact is deliberately generated, not committed.
import { createFaroApp } from "../_faroApp.mjs";

const app = createFaroApp();

export default app;
