import FaroLogo from "@/components/FaroLogo";
import { Button } from "@/components/ui/button";
import { getProductStage, PRODUCT_INTRO_PATH, productStages } from "@/lib/productIntro";
import { motion, useReducedMotion } from "framer-motion";
import { ArrowDown, ArrowRight, Bot, Check, ChevronRight, CircleDot, Compass, Eye, Layers3, Radar, ShieldCheck, Sparkles, Target, X } from "lucide-react";
import { useState } from "react";
import { useLocation } from "wouter";

const colourThemes = {
  terracotta: { accent: "#bf6348", glow: "rgba(191,99,72,0.26)", soft: "#f8e3d1", text: "#8f4532" },
  gold: { accent: "#bc8a31", glow: "rgba(188,138,49,0.22)", soft: "#f8edcf", text: "#85611e" },
  sage: { accent: "#5f9076", glow: "rgba(95,144,118,0.22)", soft: "#deede1", text: "#37664f" },
};

export default function ProductIntro() {
  const [, setLocation] = useLocation();
  const [activeStage, setActiveStage] = useState(0);
  const reduceMotion = useReducedMotion();
  const stage = getProductStage(activeStage);
  const theme = colourThemes[stage.color];

  return <main className="min-h-screen overflow-hidden bg-[#fffaf2] text-[#31231b]">
    <nav className="relative z-20 mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8 lg:px-10">
      <button onClick={() => setLocation("/")} className="rounded-xl outline-none transition active:scale-[0.97] focus-visible:ring-2 focus-visible:ring-[#bb654a]" aria-label="Open Faro AI workspace"><FaroLogo className="[&>span:first-child]:h-10 [&>span:first-child]:w-10 [&>span:first-child]:rounded-[13px] [&>span:last-child]:text-[21px]" /></button>
      <Button onClick={() => setLocation("/")} className="h-10 rounded-xl bg-[#b85f45] px-4 text-xs font-extrabold text-white shadow-[0_8px_20px_rgba(161,80,55,0.2)] hover:bg-[#9e4e37]">Open Discover <ArrowRight className="ml-2 h-3.5 w-3.5" /></Button>
    </nav>

    <section className="relative mx-auto grid max-w-7xl gap-10 px-5 pb-20 pt-8 sm:px-8 lg:grid-cols-[1.02fr_0.98fr] lg:items-center lg:px-10 lg:pb-28 lg:pt-16">
      <div className="pointer-events-none absolute -left-24 top-[-180px] h-[540px] w-[540px] rounded-full bg-[#f5ddc5]/65 blur-3xl" />
      <div className="pointer-events-none absolute right-[-150px] top-[80px] h-[500px] w-[500px] rounded-full bg-[#e5efe1]/60 blur-3xl" />
      <div className="relative z-10"><motion.div initial={reduceMotion ? false : { opacity: 0, y: 14 }} animate={reduceMotion ? {} : { opacity: 1, y: 0 }} transition={{ duration: 0.46, ease: [0.23, 1, 0.32, 1] }} className="inline-flex items-center gap-2 rounded-full border border-[#ead5c1] bg-white/80 px-3 py-1.5 text-[10px] font-extrabold uppercase tracking-[0.16em] text-[#9a593f] shadow-sm"><span className="h-1.5 w-1.5 rounded-full bg-[#bb6348]" />The focused way to find demand on X</motion.div><motion.h1 initial={reduceMotion ? false : { opacity: 0, y: 16 }} animate={reduceMotion ? {} : { opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: 0.06, ease: [0.23, 1, 0.32, 1] }} className="mt-6 max-w-3xl text-5xl font-extrabold leading-[0.95] tracking-[-0.085em] text-[#34231a] sm:text-6xl lg:text-7xl">The signal is there.<br /><span className="text-[#b85f45]">Faro finds it.</span></motion.h1><motion.p initial={reduceMotion ? false : { opacity: 0, y: 16 }} animate={reduceMotion ? {} : { opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: 0.12, ease: [0.23, 1, 0.32, 1] }} className="mt-6 max-w-xl text-[15px] leading-7 text-[#705c4e] sm:text-base">A calm signal desk for finding credible people seeking AI workflows, automation, implementation, and practical AI video help—without turning your process into automatic outreach.</motion.p><motion.div initial={reduceMotion ? false : { opacity: 0, y: 16 }} animate={reduceMotion ? {} : { opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: 0.18, ease: [0.23, 1, 0.32, 1] }} className="mt-8 flex flex-wrap items-center gap-3"><Button onClick={() => setLocation("/")} className="h-12 rounded-2xl bg-[#b85f45] px-5 text-xs font-extrabold text-white shadow-[0_10px_22px_rgba(161,80,55,0.24)] hover:bg-[#9e4e37]">Enter your signal desk <ArrowRight className="ml-2 h-4 w-4" /></Button><button onClick={() => document.getElementById("how-faro-works")?.scrollIntoView({ behavior: "smooth" })} className="inline-flex h-12 items-center gap-2 rounded-2xl px-3 text-xs font-bold text-[#765742] transition hover:bg-[#fbefe1]"><ArrowDown className="h-4 w-4" />See how Faro works</button></motion.div><div className="mt-10 flex flex-wrap gap-2.5"><TrustPill icon={Radar} label="On-demand live checks" /><TrustPill icon={ShieldCheck} label="Human-led decisions" /><TrustPill icon={Target} label="Intent-first ranking" /></div></div>
      <motion.div initial={reduceMotion ? false : { opacity: 0, scale: 0.96, y: 16 }} animate={reduceMotion ? {} : { opacity: 1, scale: 1, y: 0 }} transition={{ duration: 0.7, delay: 0.16, ease: [0.23, 1, 0.32, 1] }} className="relative z-10 mx-auto w-full max-w-[570px]"><SignalOrbital activeStage={activeStage} reduceMotion={Boolean(reduceMotion)} /><div className="pointer-events-none absolute -bottom-6 left-[8%] right-[8%] h-12 rounded-full bg-[#976049]/15 blur-2xl" /></motion.div>
    </section>

    <section id="how-faro-works" className="relative border-y border-[#eadccf] bg-[#fffdf9] py-20 sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className="max-w-2xl"><p className="text-[10px] font-extrabold uppercase tracking-[0.18em] text-[#a35d44]">One calm system, three deliberate moves</p><h2 className="mt-4 text-3xl font-extrabold tracking-[-0.065em] sm:text-5xl">A better path from signal to decision.</h2></div><div className="mt-10 grid gap-3 lg:grid-cols-[0.78fr_1.22fr]"> <div className="grid gap-2 sm:grid-cols-3 lg:grid-cols-1">{productStages.map((item, index) => { const itemTheme = colourThemes[item.color]; const selected = index === activeStage; return <button key={item.eyebrow} onClick={() => setActiveStage(index)} className={`group rounded-2xl border p-4 text-left transition duration-200 ${selected ? "border-transparent bg-[#fff8ef] shadow-[0_12px_28px_rgba(93,58,34,0.09)]" : "border-[#eee1d5] bg-white hover:-translate-y-0.5 hover:border-[#e6c5ad]"}`} style={selected ? { boxShadow: `0 14px 32px ${itemTheme.glow}` } : undefined}><div className="flex items-center justify-between"><span className="text-[10px] font-extrabold uppercase tracking-[0.14em]" style={{ color: itemTheme.text }}>{item.eyebrow}</span><ChevronRight className={`h-4 w-4 transition ${selected ? "translate-x-0" : "-translate-x-1 opacity-0 group-hover:translate-x-0 group-hover:opacity-100"}`} style={{ color: itemTheme.accent }} /></div><p className="mt-2 text-sm font-extrabold tracking-[-0.035em]">{item.title.split(".")[0]}.</p></button>})}</div><motion.article key={stage.eyebrow} initial={reduceMotion ? false : { opacity: 0, y: 12 }} animate={reduceMotion ? {} : { opacity: 1, y: 0 }} transition={{ duration: 0.28, ease: [0.23, 1, 0.32, 1] }} className="relative overflow-hidden rounded-[30px] border border-[#eadccf] bg-[#fcf5eb] p-6 sm:p-9"><div className="pointer-events-none absolute right-[-80px] top-[-110px] h-64 w-64 rounded-full blur-3xl" style={{ background: theme.glow }} /><div className="relative grid gap-8 md:grid-cols-[1fr_0.8fr] md:items-end"><div><p className="text-[10px] font-extrabold uppercase tracking-[0.16em]" style={{ color: theme.text }}>{stage.eyebrow}</p><h3 className="mt-3 max-w-lg text-3xl font-extrabold leading-[1.02] tracking-[-0.065em] sm:text-4xl">{stage.title}</h3><p className="mt-4 max-w-lg text-sm leading-6 text-[#715a49]">{stage.description}</p><span className="mt-6 inline-flex rounded-full px-3 py-1.5 text-[10px] font-extrabold" style={{ backgroundColor: theme.soft, color: theme.text }}>{stage.chip}</span></div><ProductStageGraphic index={activeStage} accent={theme.accent} soft={theme.soft} reduceMotion={Boolean(reduceMotion)} /></div></motion.article></div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-24 lg:px-10"><div className="grid gap-4 md:grid-cols-3"><CapabilityCard icon={Compass} title="One clear brief" text="Tell Faro who you want to find. The agent turns it into a focused listening task." tone="peach" /><CapabilityCard icon={Layers3} title="Reasons, not mystery" text="See the signal evidence that brought each post forward before you decide." tone="cream" /><CapabilityCard icon={Eye} title="Full context, inside Faro" text="Open a complete post, inspect the AI read, then Keep or Dismiss it yourself." tone="sage" /></div><div className="mt-20 overflow-hidden rounded-[32px] bg-[#38261d] p-7 text-white sm:p-10"><div className="relative"><div className="pointer-events-none absolute -right-12 -top-20 h-60 w-60 rounded-full bg-[#d67d5c]/25 blur-3xl" /><div className="relative grid gap-8 md:grid-cols-[1fr_auto] md:items-end"><div><p className="text-[10px] font-extrabold uppercase tracking-[0.18em] text-[#e9b99d]">Signal intelligence, human judgment</p><h2 className="mt-4 max-w-2xl text-4xl font-extrabold leading-[0.98] tracking-[-0.07em] sm:text-5xl">Start with the people already asking for help.</h2><p className="mt-4 max-w-xl text-sm leading-6 text-white/62">Faro AI keeps live-source outcomes visible, ranking accountable, and every external action firmly in your hands.</p></div><Button onClick={() => setLocation("/")} className="h-12 rounded-2xl bg-[#f5c9a9] px-5 text-xs font-extrabold text-[#4a2c1e] hover:bg-[#ffe0c7]">Go to Discover <ArrowRight className="ml-2 h-4 w-4" /></Button></div></div></div></section>
    <footer className="border-t border-[#eadccf] px-5 py-6 text-center text-[10px] font-semibold text-[#9e8370]">Faro AI · focused social listening for service demand · <button onClick={() => setLocation("/")} className="underline decoration-[#d5b69d] underline-offset-4 hover:text-[#7b503c]">Open workspace</button></footer>
  </main>;
}

function SignalOrbital({ activeStage, reduceMotion }: { activeStage: number; reduceMotion: boolean }) {
  const stage = getProductStage(activeStage);
  const theme = colourThemes[stage.color];
  return <div className="relative aspect-square min-h-[360px] rounded-[42px] border border-[#ecd9c8] bg-[radial-gradient(circle_at_50%_40%,#fffdf9_0%,#f9eddf_50%,#f3ddca_100%)] shadow-[0_28px_50px_rgba(91,56,32,0.12)] sm:min-h-[480px]"><div className="absolute inset-[8%] rounded-[36px] border border-white/70 bg-white/20" /><motion.div animate={reduceMotion ? {} : { rotate: 360 }} transition={{ duration: 30, ease: "linear", repeat: Infinity }} className="absolute inset-[14%] rounded-full border border-dashed border-[#d39a79]/70" /><motion.div animate={reduceMotion ? {} : { rotate: -360 }} transition={{ duration: 22, ease: "linear", repeat: Infinity }} className="absolute inset-[25%] rounded-full border border-[#d7c5ae]" /><motion.div animate={reduceMotion ? {} : { y: [0, -14, 0], rotate: [-1.5, 1.5, -1.5] }} transition={{ duration: 5.2, ease: "easeInOut", repeat: Infinity }} className="absolute left-[17%] top-[17%] h-20 w-20 rounded-[22px] border border-white/80 bg-white/90 p-2 shadow-[0_18px_28px_rgba(93,57,31,0.14)] sm:h-24 sm:w-24"><div className="flex h-full flex-col justify-between rounded-[16px] bg-[#fff7ef] p-2"><span className="h-2 w-9 rounded-full bg-[#c67559]/45" /><span className="h-2 w-12 rounded-full bg-[#c67559]/20" /><span className="flex items-center gap-1 text-[8px] font-extrabold text-[#a85a42]"><CircleDot className="h-2.5 w-2.5" />Need intent</span></div></motion.div><motion.div animate={reduceMotion ? {} : { y: [0, 12, 0], rotate: [1.5, -1.5, 1.5] }} transition={{ duration: 6, ease: "easeInOut", repeat: Infinity }} className="absolute bottom-[17%] right-[15%] w-28 rounded-[20px] border border-white/80 bg-white/90 p-3 shadow-[0_18px_28px_rgba(93,57,31,0.14)] sm:w-32"><div className="flex items-center gap-2"><span className="grid h-6 w-6 place-items-center rounded-lg bg-[#e4f0e5] text-[#4d8668]"><Check className="h-3.5 w-3.5" /></span><div><p className="text-[9px] font-extrabold">Qualified</p><p className="text-[8px] text-[#8c7665]">real request</p></div></div></motion.div><div className="absolute left-1/2 top-1/2 grid h-[32%] w-[32%] -translate-x-1/2 -translate-y-1/2 place-items-center rounded-[30px] border-[10px] border-white/70 bg-[#3a281e] shadow-[0_28px_30px_rgba(67,39,24,0.27)]"><motion.div animate={reduceMotion ? {} : { rotate: [0, 8, -8, 0] }} transition={{ duration: 5, ease: "easeInOut", repeat: Infinity }} className="grid h-[72%] w-[72%] place-items-center rounded-[22px]" style={{ backgroundColor: theme.accent, boxShadow: `0 0 48px ${theme.glow}` }}><Sparkles className="h-9 w-9 text-white sm:h-11 sm:w-11" /></motion.div></div><div className="absolute bottom-[9%] left-1/2 -translate-x-1/2 rounded-full border border-white/70 bg-white/75 px-3 py-1.5 text-[9px] font-extrabold uppercase tracking-[0.13em] backdrop-blur" style={{ color: theme.text }}>{stage.chip}</div></div>;
}

function ProductStageGraphic({ index, accent, soft, reduceMotion }: { index: number; accent: string; soft: string; reduceMotion: boolean }) {
  const icons = [Radar, Target, ShieldCheck];
  const Icon = icons[index];
  return <motion.div animate={reduceMotion ? {} : { y: [0, -7, 0] }} transition={{ duration: 4, ease: "easeInOut", repeat: Infinity }} className="relative mx-auto grid aspect-square w-full max-w-[220px] place-items-center rounded-[30px] border border-white/80 bg-white/65 shadow-[0_18px_34px_rgba(94,60,36,0.09)]"><motion.div animate={reduceMotion ? {} : { rotate: 360 }} transition={{ duration: 18, ease: "linear", repeat: Infinity }} className="absolute inset-[14%] rounded-full border border-dashed" style={{ borderColor: `${accent}70` }} /><div className="grid h-20 w-20 place-items-center rounded-[25px] border-[6px] border-white shadow-lg" style={{ backgroundColor: soft }}><Icon className="h-8 w-8" style={{ color: accent }} /></div><span className="absolute -bottom-3 rounded-full bg-[#3a281e] px-3 py-1 text-[9px] font-extrabold uppercase tracking-[0.12em] text-white">Faro AI</span></motion.div>;
}

function TrustPill({ icon: Icon, label }: { icon: typeof Radar; label: string }) { return <span className="inline-flex items-center gap-1.5 rounded-full border border-[#eadaca] bg-white/75 px-3 py-2 text-[10px] font-bold text-[#775b49]"><Icon className="h-3.5 w-3.5 text-[#a75b43]" />{label}</span>; }

function CapabilityCard({ icon: Icon, title, text, tone }: { icon: typeof Compass; title: string; text: string; tone: "peach" | "cream" | "sage" }) { const tones = { peach: "bg-[#f9e6d7] text-[#a85b40]", cream: "bg-[#f8edcf] text-[#927020]", sage: "bg-[#e2eee4] text-[#4d8066]" }; return <motion.article whileHover={{ y: -5 }} transition={{ duration: 0.2, ease: [0.23, 1, 0.32, 1] }} className="rounded-[28px] border border-[#eadfd4] bg-white p-6 shadow-[0_12px_25px_rgba(98,59,34,0.045)]"><span className={`grid h-11 w-11 place-items-center rounded-2xl ${tones[tone]}`}><Icon className="h-5 w-5" /></span><h3 className="mt-7 text-xl font-extrabold tracking-[-0.05em]">{title}</h3><p className="mt-3 text-sm leading-6 text-[#796657]">{text}</p></motion.article>; }

export { PRODUCT_INTRO_PATH };
