import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Bot, ChevronRight, LogOut, ShieldCheck, UserRound } from "lucide-react";

export default function Profile() { const { user, logout } = useAuth(); const initial = user?.name?.charAt(0).toUpperCase() || "F"; return <DashboardLayout><div className="mx-auto max-w-4xl pb-8"><header className="flex items-center gap-3 border-b border-[#e8e9e5] pb-5"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-[#111214] text-white"><UserRound className="h-4 w-4" /></span><div><h1 className="text-xl font-extrabold tracking-[-0.055em]">Profile</h1><p className="text-[11px] text-[#858780]">Your Faro account and operating guardrails.</p></div></header><section className="mt-6 rounded-[26px] border border-[#e4e6e1] bg-white p-5 sm:p-7"><div className="flex flex-wrap items-center gap-4"><Avatar className="h-16 w-16"><AvatarFallback className="bg-[#dff5e6] text-lg font-extrabold text-[#17643c]">{initial}</AvatarFallback></Avatar><div className="min-w-0"><h2 className="truncate text-lg font-extrabold tracking-[-0.04em]">{user?.name || "Faro member"}</h2><p className="mt-1 truncate text-sm text-[#777a73]">{user?.email || "Private Faro account"}</p></div></div><div className="mt-7 grid gap-2 sm:grid-cols-3"><ProfileTile icon={Bot} label="Agent mode" value="On demand" /><ProfileTile icon={ShieldCheck} label="External action" value="Human-led" /><ProfileTile icon={UserRound} label="Account" value="Private" /></div></section><section className="mt-4 rounded-2xl border border-[#e5e6e2] bg-white"><div className="flex items-center justify-between px-4 py-4"><div><p className="text-sm font-bold">Session</p><p className="mt-1 text-[10px] text-[#8e9089]">Sign out on this device.</p></div><Button onClick={logout} variant="outline" className="h-9 rounded-lg px-3 text-xs text-[#a14941]"><LogOut className="mr-1.5 h-3.5 w-3.5" />Sign out</Button></div></section></div></DashboardLayout>; }

function ProfileTile({ icon: Icon, label, value }: { icon: typeof Bot; label: string; value: string }) { return <div className="rounded-2xl bg-[#f4f5f2] p-3"><Icon className="h-4 w-4 text-[#486e53]" /><p className="mt-4 text-[9px] font-bold uppercase tracking-[0.14em] text-[#90928b]">{label}</p><p className="mt-1 text-sm font-bold">{value}</p></div>; }
