import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { getQualifiedPosts } from "@/lib/discoverFeed";
import { buildReviewDialogContent } from "@/lib/discoverAgent";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, Check, CircleCheck, CircleX, ExternalLink, Inbox, Lightbulb, ListFilter, Loader2, RefreshCw, ThumbsDown, ThumbsUp } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";

type FeedStatus = "all" | "pending" | "approved" | "rejected";

export default function ReviewQueue() {
  const utils = trpc.useUtils();
  const [location, setLocation] = useLocation();
  const params = new URLSearchParams(location.split("?")[1] || "");
  const initialPostId = Number(params.get("post")) || null;
  const [filter, setFilter] = useState<FeedStatus>("pending");
  const [selectedId, setSelectedId] = useState<number | null>(initialPostId);
  const overview = trpc.monitoring.overview.useQuery(undefined, { refetchInterval: 30_000 });
  const activeBrief = overview.data?.monitors.find(({ monitor }) => monitor.status === "active") ?? overview.data?.monitors[0];
  const qualified = useMemo(() => getQualifiedPosts(overview.data?.posts ?? [], activeBrief?.monitor.id), [overview.data?.posts, activeBrief?.monitor.id]);
  const posts = useMemo(() => qualified.filter(({ post }) => filter === "all" || post.reviewStatus === filter), [qualified, filter]);
  const selected = posts.find(({ post }) => post.id === selectedId) ?? posts.find(({ post }) => post.id === initialPostId) ?? posts[0] ?? null;
  const sync = trpc.monitoring.sync.useMutation({ onSuccess: async result => { await utils.monitoring.overview.invalidate(); toast.success(`${result.inserted} new posts checked.`); }, onError: error => toast.error(error.message) });
  const review = trpc.monitoring.review.useMutation({ onSuccess: async () => { await utils.monitoring.overview.invalidate(); toast.success("Review decision saved."); }, onError: error => toast.error(error.message) });
  useEffect(() => { if (selected && selected.post.id !== selectedId) setSelectedId(selected.post.id); }, [selected, selectedId]);

  const counts = { all: qualified.length, pending: qualified.filter(({ post }) => post.reviewStatus === "pending").length, approved: qualified.filter(({ post }) => post.reviewStatus === "approved").length, rejected: qualified.filter(({ post }) => post.reviewStatus === "rejected").length };
  return <div className="mx-auto max-w-7xl pb-8"><header className="flex flex-wrap items-center justify-between gap-4 border-b border-[#eadfd2] pb-5"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-[#f1d7b9] text-[#8f4e38]"><Inbox className="h-4 w-4" /></span><div><p className="text-[10px] font-extrabold uppercase tracking-[0.15em] text-[#a25d47]">Human review workspace</p><h1 className="mt-0.5 text-xl font-extrabold tracking-[-0.055em]">Review qualified requests</h1></div></div><div className="flex items-center gap-2"><Button onClick={() => setLocation("/")} variant="outline" className="h-9 rounded-xl border-[#e4cfbc] bg-white px-3 text-xs font-bold text-[#81523d] hover:bg-[#fff8ef]"><ArrowLeft className="mr-1.5 h-3.5 w-3.5" />Discover</Button><button onClick={() => activeBrief && sync.mutate({ monitorId: activeBrief.monitor.id })} disabled={!activeBrief || sync.isPending} className="grid h-9 w-9 place-items-center rounded-xl border border-[#e8dacc] bg-white text-[#765d4a] hover:bg-[#fff8ef] disabled:opacity-40" title="Check live source"><RefreshCw className={`h-4 w-4 ${sync.isPending ? "animate-spin" : ""}`} /></button></div></header>
    <section className="mt-5 grid gap-4 xl:grid-cols-[minmax(330px,0.9fr)_minmax(0,1.1fr)]"><div className="min-w-0"><div className="flex items-center justify-between gap-3 rounded-[20px] border border-[#eadfd2] bg-white p-2"><div className="flex min-w-0 gap-1 overflow-x-auto scrollbar-none"><ReviewFilter icon={ListFilter} label="All" count={counts.all} active={filter === "all"} onClick={() => setFilter("all")} /><ReviewFilter icon={Lightbulb} label="Pending" count={counts.pending} active={filter === "pending"} onClick={() => setFilter("pending")} /><ReviewFilter icon={CircleCheck} label="Kept" count={counts.approved} active={filter === "approved"} onClick={() => setFilter("approved")} /><ReviewFilter icon={CircleX} label="Dismissed" count={counts.rejected} active={filter === "rejected"} onClick={() => setFilter("rejected")} /></div></div><div className="mt-3 overflow-hidden rounded-[22px] border border-[#eadfd2] bg-white">{overview.isLoading ? <div className="grid min-h-72 place-items-center"><Loader2 className="h-5 w-5 animate-spin text-[#b6a697]" /></div> : posts.length ? posts.map(item => <ReviewRow key={item.post.id} item={item} selected={item.post.id === selected?.post.id} onSelect={() => setSelectedId(item.post.id)} />) : <div className="grid min-h-72 place-items-center p-6 text-center"><Inbox className="h-5 w-5 text-[#b2a596]" /><p className="mt-3 text-sm font-bold">Nothing in this view.</p><p className="mt-1 text-[10px] text-[#9d8e80]">Change the filter or run a fresh Discover search.</p></div>}</div></div><div className="min-w-0">{selected ? <ReviewDetail item={selected} pending={review.isPending} onReview={decision => review.mutate({ postId: selected.post.id, decision })} /> : <div className="grid min-h-72 place-items-center rounded-[24px] border border-dashed border-[#eadfd2] bg-[#fffdfa] p-6 text-center"><Inbox className="h-5 w-5 text-[#b2a596]" /><p className="mt-3 text-sm font-bold">Choose a request to review.</p></div>}</div></section>
  </div>;
}

function ReviewFilter({ icon: Icon, label, count, active, onClick }: { icon: typeof Inbox; label: string; count: number; active: boolean; onClick: () => void }) { return <button onClick={onClick} className={`flex shrink-0 items-center gap-1.5 rounded-xl px-2.5 py-2 text-[10px] font-bold transition ${active ? "bg-[#f1d7b9] text-[#75432e]" : "text-[#897464] hover:bg-[#fff8ef]"}`}><Icon className="h-3.5 w-3.5" />{label}<span className="rounded-full bg-white/70 px-1.5 py-0.5 text-[9px]">{count}</span></button>; }
function ReviewRow({ item, selected, onSelect }: { item: any; selected: boolean; onSelect: () => void }) { const { post } = item; const author = post.authorName || post.authorHandle || "Unknown source"; return <button onClick={onSelect} className={`flex w-full items-start gap-3 border-b border-[#f1e7de] p-4 text-left transition ${selected ? "bg-[#fff4e8]" : "hover:bg-[#fffaf5]"}`}><Avatar className="h-9 w-9 shrink-0"><AvatarImage src={post.authorAvatarUrl || undefined} alt="" /><AvatarFallback className="bg-[#f7e1c9] text-[10px] font-bold text-[#99583f]">{author.charAt(0).toUpperCase()}</AvatarFallback></Avatar><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-3"><p className="truncate text-xs font-extrabold text-[#3d2e23]">{author}</p><span className="rounded-full bg-[#e7f3e9] px-2 py-0.5 text-[9px] font-extrabold text-[#3f7757]">{post.ruleScore}</span></div><p className="mt-1 max-h-10 overflow-hidden text-[10px] leading-5 text-[#806b5c]">{post.body}</p></div></button>; }
function ReviewDetail({ item, pending, onReview }: { item: any; pending: boolean; onReview: (decision: "approved" | "rejected") => void }) { const { post, monitorName } = item; const detail = buildReviewDialogContent(post); const initial = detail.authorLabel.charAt(0).toUpperCase() || "F"; return <article className="overflow-hidden rounded-[24px] border border-[#eadfd2] bg-white xl:sticky xl:top-7 xl:flex xl:max-h-[calc(100vh-5rem)] xl:flex-col"><div className="shrink-0 border-b border-[#eee0d4] bg-[#fffaf5] p-5 sm:p-6"><div className="flex items-center gap-3"><Avatar className="h-11 w-11"><AvatarImage src={post.authorAvatarUrl || undefined} alt="" /><AvatarFallback className="bg-[#f8e4c8] font-bold text-[#9c573f]">{initial}</AvatarFallback></Avatar><div className="min-w-0"><p className="truncate text-sm font-extrabold">{detail.authorLabel}</p><p className="mt-0.5 truncate text-[10px] text-[#9a8a7b]">{detail.handleLabel} · {monitorName}</p></div><span className="ml-auto rounded-full bg-[#e7f3e9] px-2.5 py-1 text-[10px] font-extrabold text-[#3f7757]">{post.ruleScore}</span></div></div><div className="min-h-0 p-5 sm:p-6 xl:flex-1 xl:overflow-y-auto scrollbar-none"><p className="whitespace-pre-wrap text-[15px] leading-7 text-[#3b2d23]">{detail.fullPost}</p><div className="mt-6 rounded-2xl bg-[#fbf2e7] p-4"><p className="text-[10px] font-extrabold uppercase tracking-[0.14em] text-[#a25d47]">Faro AI read</p><p className="mt-2 text-sm font-extrabold text-[#4b2e21]">{detail.agentRead.confidence}</p><p className="mt-2 text-[12px] leading-5 text-[#765845]">{detail.agentRead.summary}</p></div></div><div className="shrink-0 border-t border-[#eee0d4] bg-white p-4 sm:px-6"><div className="flex flex-wrap items-center gap-2"><a href={post.postUrl || "https://x.com"} target="_blank" rel="noreferrer" className="inline-flex h-11 items-center rounded-xl border border-[#e5d3bd] px-4 text-xs font-bold text-[#794b36] hover:bg-[#fbf2e5]"><ExternalLink className="mr-2 h-4 w-4" />Open in X</a>{post.reviewStatus === "pending" ? <><Button disabled={pending} onClick={() => onReview("approved")} className="h-11 rounded-xl bg-[#b85f45] px-4 text-xs font-extrabold text-white hover:bg-[#9f4d36]"><ThumbsUp className="mr-2 h-4 w-4" />Keep</Button><Button disabled={pending} onClick={() => onReview("rejected")} variant="outline" className="h-11 rounded-xl border-[#eed5cc] px-4 text-xs font-bold text-[#a14941] hover:bg-[#fff4f0]"><ThumbsDown className="mr-2 h-4 w-4" />Dismiss</Button></> : <span className="inline-flex h-11 items-center rounded-xl bg-[#f1e2d0] px-4 text-xs font-bold text-[#8f4e38]">{post.reviewStatus === "approved" ? <Check className="mr-1.5 h-3.5 w-3.5" /> : null}Already {post.reviewStatus}</span>}</div></div></article>; }
