import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowUpRight, Check, CircleCheck, CircleX, Inbox, Lightbulb, ListFilter, Loader2, ThumbsDown, ThumbsUp } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

type FeedStatus = "all" | "pending" | "approved" | "rejected";
const scoreTone = (score: number) => score >= 80 ? "bg-[#dff5e6] text-[#17643c]" : "bg-[#f2f3f0] text-[#30322e]";

export default function ReviewQueue() {
  const utils = trpc.useUtils();
  const [filter, setFilter] = useState<FeedStatus>("pending");
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const overview = trpc.monitoring.overview.useQuery(undefined, { refetchInterval: 30_000 });
  const review = trpc.monitoring.review.useMutation({ onSuccess: () => { utils.monitoring.overview.invalidate(); toast.success("Saved."); }, onError: error => toast.error(error.message) });
  const activeBrief = overview.data?.monitors.find(({ monitor }) => monitor.status === "active") ?? overview.data?.monitors[0];
  const posts = useMemo(() => (overview.data?.posts ?? []).filter(({ post, monitor }) => post.source !== "demo" && (!activeBrief || monitor.id === activeBrief.monitor.id) && (filter === "all" || post.reviewStatus === filter) && post.ruleScore >= 60), [overview.data?.posts, activeBrief, filter]);
  const selected = posts.find(({ post }) => post.id === selectedId) ?? posts[0] ?? null;

  return <DashboardLayout><div className="mx-auto max-w-6xl pb-8"><header className="flex items-center justify-between border-b border-[#e8e9e5] pb-5"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-[#111214] text-white"><Inbox className="h-4 w-4" /></span><div><h1 className="text-xl font-extrabold tracking-[-0.055em]">Review</h1><p className="text-[11px] text-[#858780]">Keep only requests worth pursuing.</p></div></div><div className="flex items-center gap-1"><FilterButton icon={ListFilter} active={filter === "all"} label="All" onClick={() => setFilter("all")} /><FilterButton icon={Lightbulb} active={filter === "pending"} label="Pending" onClick={() => setFilter("pending")} /><FilterButton icon={CircleCheck} active={filter === "approved"} label="Kept" onClick={() => setFilter("approved")} /><FilterButton icon={CircleX} active={filter === "rejected"} label="Dismissed" onClick={() => setFilter("rejected")} /></div></header>
    <section className={`mt-5 grid gap-4 ${selected ? "xl:grid-cols-[minmax(0,1fr)_360px]" : ""}`}><div className="overflow-hidden rounded-2xl border border-[#e5e6e2] bg-white"><div className="divide-y divide-[#eff0ed]">{overview.isLoading && <div className="grid min-h-72 place-items-center"><Loader2 className="h-5 w-5 animate-spin text-[#9ca097]" /></div>}{!overview.isLoading && !posts.length && <div className="grid min-h-72 place-items-center p-6 text-center"><Inbox className="h-5 w-5 text-[#b2b5ae]" /><p className="mt-3 text-sm font-bold">Your queue is clear.</p></div>}{posts.map(({ post, monitorName }) => <button key={post.id} onClick={() => setSelectedId(post.id)} className={`grid w-full gap-3 px-4 py-3.5 text-left transition sm:grid-cols-[40px_1fr_auto] ${selected?.post.id === post.id ? "bg-[#f6f8f5]" : "hover:bg-[#fafbf9]"}`}><span className={`grid h-10 w-10 place-items-center rounded-xl text-xs font-extrabold ${scoreTone(post.ruleScore)}`}>{post.ruleScore}</span><div className="min-w-0"><div className="flex items-center gap-2"><span className="text-xs font-bold">{post.authorHandle ? `@${post.authorHandle}` : post.authorName || "Unknown"}</span><span className="text-[9px] text-[#999b95]">{monitorName}</span></div><p className="mt-1 line-clamp-2 text-sm leading-5 text-[#343633]">{post.body}</p></div><span className="pt-1 text-[9px] font-bold uppercase text-[#a1a39c]">{post.reviewStatus}</span></button>)}</div></div>{selected && <aside className="rounded-2xl border border-[#e5e6e2] bg-white p-4"><ReviewPanel item={selected} pending={review.isPending} onReview={decision => review.mutate({ postId: selected.post.id, decision })} /></aside>}</section></div></DashboardLayout>;
}

function FilterButton({ icon: Icon, active, label, onClick }: { icon: typeof Inbox; active: boolean; label: string; onClick: () => void }) { return <button title={label} aria-label={label} onClick={onClick} className={`grid h-8 w-8 place-items-center rounded-lg ${active ? "bg-[#111214] text-white" : "text-[#7d8079] hover:bg-[#f1f2ef]"}`}><Icon className="h-3.5 w-3.5" /></button>; }

function ReviewPanel({ item, pending, onReview }: { item: { post: any; monitorName: string }; pending: boolean; onReview: (decision: "approved" | "rejected") => void }) { const { post, monitorName } = item; const timing = (post.scoreExplanation as Array<{ label: string; points: number }>).find(reason => reason.label === "Timing signal" && reason.points > 0); return <div><div className="flex items-center justify-between"><div><p className="text-xs font-bold">{post.authorHandle ? `@${post.authorHandle}` : post.authorName || "Unknown"}</p><p className="mt-1 text-[9px] text-[#969890]">{monitorName}</p></div><span className={`grid h-9 w-9 place-items-center rounded-xl text-xs font-extrabold ${scoreTone(post.ruleScore)}`}>{post.ruleScore}</span></div><div className="mt-4 rounded-xl bg-[#f5f6f3] p-3"><p className="text-sm leading-6 text-[#343633]">{post.body}</p><p className="mt-3 text-[10px] text-[#8b8e87]">{new Date(post.postedAt).toLocaleString()}</p></div>{timing && <span className="mt-3 inline-flex rounded-full bg-[#fff1d9] px-2 py-1 text-[9px] font-bold text-[#965b0a]">Time-sensitive</span>}<div className="mt-5 flex gap-2">{post.postUrl && <a href={post.postUrl} target="_blank" rel="noreferrer" className="grid h-9 w-9 place-items-center rounded-lg border border-[#dfe1dc]" title="Open on X"><ArrowUpRight className="h-4 w-4" /></a>}{post.reviewStatus === "pending" ? <><Button onClick={() => onReview("approved")} disabled={pending} className="h-9 flex-1 rounded-lg bg-[#187144] text-xs hover:bg-[#135f38]"><ThumbsUp className="mr-1.5 h-3.5 w-3.5" />Keep</Button><Button onClick={() => onReview("rejected")} disabled={pending} variant="outline" className="h-9 rounded-lg px-3 text-[#a14941]" title="Dismiss"><ThumbsDown className="h-3.5 w-3.5" /></Button></> : <span className="inline-flex h-9 flex-1 items-center justify-center rounded-lg bg-[#f0f1ef] text-xs font-bold text-[#696b65]"><Check className="mr-1.5 h-3.5 w-3.5" />{post.reviewStatus}</span>}</div></div>; }
